#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

SAYINGS=(
    "Bye bud\n - $USER@$HOSTNAME"
    "Sayonara son\n - $USER@$HOSTNAME"
    "Ciao cuz\n - $USER@$HOSTNAME"
    "Seeya scrub\n - $USER@$HOSTNAME"
)

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
