#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Source zenviron and zalias (source in zenviron)
if [[ -s "$HOME/.zenviron" ]]; then
    source "$HOME/.zenviron"
fi

## Source fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

## Source z
if [[ -f "$HOME/.zfzfzf/z/z.sh" ]]; then
    source "$HOME/.zfzfzf/z/z.sh"
fi

## Source fz (only after sourcing z and fzf)
if [[ -f "$HOME/.zfzfzf/fz/fz.sh" ]]; then
    source "$HOME/.zfzfzf/fz/fz.sh"
fi

## zsh completions
fpath=("$HOME/.dotfiles/mod/zsh/zsh-completions/src" $fpath)
rm -f ~/.zcompdump

