#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
## Source the aliases
if [[ -s "$HOME/.zalias" ]]; then
    source "$HOME/.zalias"
fi

## Source customizations
if [[ -s "$HOME/.zenviron" ]]; then
    source "$HOME/.zenviron"
fi

## Added by fzf install script.
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
